// Authentication
export const UPDATE_AUTHENTICATED = 'UPDATE_AUTHENTICATED';

// Contact actions
export const UPDATE_CONTACT_INFORMATION = 'UPDATE_CONTACT_INFORMATION';
export const REMOVE_CONTACT_INFORMATION = 'REMOVE_CONTACT_INFORMATION';
