// Authentication
export const UPDATE_AUTHENTICATED = 'UPDATE_AUTHENTICATED';

// Contact actions
export const UPDATE_CONTACT_INFORMATION = 'UPDATE_CONTACT_INFORMATION';
export const REMOVE_CONTACT_INFORMATION = 'REMOVE_CONTACT_INFORMATION';

// Notifications
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

// Announcements
export const UPDATE_ANNOUNCEMENTS = 'UPDATE_ANNOUNCEMENTS';
export const REMOVE_ANNOUNCEMENT = 'REMOVE_ANNOUNCEMENT';

// Profile
export const UPDATE_VOLUNTEER_PROFILE = 'UPDATE_VOLUNTEER_PROFILE';
export const REMOVE_VOLUNTEER_PROFILE = 'REMOVE_VOLUNTEER_PROFILE';

// Projects & Project
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
