#%RAML 1.0
title: Projects endpoint
version: 1
protocols: [ HTTP ]
baseUri: api/{version}/projects
mediaType: application/json

/active:
  get:
    description: Get a array of projects of all active projects
    example: !include projects.json
    responses:
      200:
        body:
          application/json:
            type: !include projectsReponse.json
            example: !include projects.json
/all:
  get:
    description: Get a array of projects of all projects
    responses:
      200:
        body:
          application/json:
            type: !include projectsReponse.json
            example: !include projects.json

/category/{category_id}:
  get:
    description: Get a array of projects of all projects by category id
    example: !include projects.json
    responses:
      200:
        body:
          application/json:
            type: !include projectsReponse.json
            example: !include projects.json
/hidden:
  get:
    description: Get a array of projects of all projects that are hidden
    example: !include projects.json
    responses:
      200:
        body:
          application/json:
            type: !include projectsReponse.json
            example: !include projects.json
/status/{status_id}:
  get:
    description: Get a array of projects of all projects by status id
    example: !include projects.json
    responses:
      200:
        body:
          application/json:
            type: !include projectsReponse.json
            example: !include projects.json
