#%RAML 1.0
title: Projects endpoint
version: 1
protocols: [ HTTP ]
baseUri: api/{version}/projects
mediaType: application/json

types:
  ActiveGet:
    type: !include projectsReponse.json
    example: !include projects.json

  AllGet:
    type: !include projectsReponse.json
    example: !include projects.json

  CategoryIdGet:
    type: !include projectsReponse.json
    example: !include projects.json

  HiddenIdGet:
    type: !include projectsReponse.json
    example: !include projects.json

  StatusGet:
    type: !include projectsReponse.json
    example: !include projects.json

/active:
  get:
    description: Get a array of projects of all active projects
    example: !include projects.json
    responses:
      200:
        body: ActiveGet

/all:
  get:
    description: Get a array of projects of all projects
    responses:
      200:
        body: AllGet

/category/{category_id}:
  get:
    description: Get a array of projects of all projects by category id
    example: !include projects.json
    responses:
      200:
        body: CategoryIdGet

/hidden:
  get:
    description: Get a array of projects of all projects that are hidden
    example: !include projects.json
    responses:
      200:
        body: HiddenIdGet

/status/{status_id}:
  get:
    description: Get a array of projects of all projects by status id
    example: !include projects.json
    responses:
      200:
        body: StatusGet
