const constants = {
  USERNAME_MAX_LENGTH: 16,
  USERNAME_MIN_LENGTH: 4,
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 24,
  EMAIL_MAX_LENGTH: 50,
  EMAIL_BODY_MAX_LENGTH: 500,
  EMAIL_BODY_MIN_LENGTH: 5,
  NAME_MIN_LENGTH: 5,
  NAME_MAX_LENGTH: 50,
};

export default constants;
